import { hashPassword } from '../auth';
import {
  User,
  Patient,
  Doctor,
  Specialization,
  DoctorSchedule,
  Appointment,
  QueueItem,
  Consultation,
  AuditLog,
  ClinicSettings,
  Notification,
  VitalSignRecord,
  LabOrder,
  BillingInvoice,
  DoctorWorkStatus,
  PreConsultationTriage,
  PharmacyItem,
  PrescriptionDispense,
  LabTestResult,
  SmsLog,
  TelemedSession,
  ClinicBranch,
  MedicalCertificate,
  DoctorReferral,
} from '../../src/types/index';

export interface DatabaseState {
  users: (User & { password_hash: string; salt: string })[];
  specializations: Specialization[];
  doctors: Doctor[];
  patients: Patient[];
  doctor_schedules: DoctorSchedule[];
  appointments: Appointment[];
  queue: QueueItem[];
  consultations: Consultation[];
  audit_logs: AuditLog[];
  clinic_settings: ClinicSettings;
  notifications: Notification[];
  vital_signs: VitalSignRecord[];
  lab_orders: LabOrder[];
  billing_invoices: BillingInvoice[];
  doctor_work_statuses: DoctorWorkStatus[];
  triages: PreConsultationTriage[];
  pharmacy_items: PharmacyItem[];
  dispense_records: PrescriptionDispense[];
  lab_results: LabTestResult[];
  sms_logs: SmsLog[];
  telemed_sessions: TelemedSession[];
  clinic_branches: ClinicBranch[];
  medical_certificates: MedicalCertificate[];
  doctor_referrals: DoctorReferral[];
}

export function getInitialSeedData(): DatabaseState {
  const adminPass = hashPassword('Admin123!');
  const doctorPass = hashPassword('Doctor123!');
  const patientPass = hashPassword('Patient123!');

  // Users
  const users: (User & { password_hash: string; salt: string })[] = [
    {
      id: 'usr_admin_001',
      email: 'admin@mediqueue.ph',
      role: 'ADMIN',
      is_active: true,
      password_hash: adminPass.hash,
      salt: adminPass.salt,
      created_at: '2026-01-01T08:00:00Z',
      updated_at: '2026-01-01T08:00:00Z',
    },
    // 5 Doctors
    {
      id: 'usr_doc_001',
      email: 'dr.santos@mediqueue.ph',
      role: 'DOCTOR',
      is_active: true,
      password_hash: doctorPass.hash,
      salt: doctorPass.salt,
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'usr_doc_002',
      email: 'dr.reyes@mediqueue.ph',
      role: 'DOCTOR',
      is_active: true,
      password_hash: doctorPass.hash,
      salt: doctorPass.salt,
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'usr_doc_003',
      email: 'dr.bautista@mediqueue.ph',
      role: 'DOCTOR',
      is_active: true,
      password_hash: doctorPass.hash,
      salt: doctorPass.salt,
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'usr_doc_004',
      email: 'dr.dizon@mediqueue.ph',
      role: 'DOCTOR',
      is_active: true,
      password_hash: doctorPass.hash,
      salt: doctorPass.salt,
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'usr_doc_005',
      email: 'dr.cruz@mediqueue.ph',
      role: 'DOCTOR',
      is_active: true,
      password_hash: doctorPass.hash,
      salt: doctorPass.salt,
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    // Sample Patients
    {
      id: 'usr_pat_001',
      email: 'juan.delacruz@example.ph',
      role: 'PATIENT',
      is_active: true,
      password_hash: patientPass.hash,
      salt: patientPass.salt,
      created_at: '2026-02-01T09:00:00Z',
      updated_at: '2026-02-01T09:00:00Z',
    },
    {
      id: 'usr_pat_002',
      email: 'bea.gonzales@example.ph',
      role: 'PATIENT',
      is_active: true,
      password_hash: patientPass.hash,
      salt: patientPass.salt,
      created_at: '2026-02-02T10:00:00Z',
      updated_at: '2026-02-02T10:00:00Z',
    },
    {
      id: 'usr_pat_003',
      email: 'sofia.reyes@example.ph',
      role: 'PATIENT',
      is_active: true,
      password_hash: patientPass.hash,
      salt: patientPass.salt,
      created_at: '2026-02-03T11:00:00Z',
      updated_at: '2026-02-03T11:00:00Z',
    },
    {
      id: 'usr_pat_004',
      email: 'joshua.ramos@example.ph',
      role: 'PATIENT',
      is_active: true,
      password_hash: patientPass.hash,
      salt: patientPass.salt,
      created_at: '2026-02-04T08:30:00Z',
      updated_at: '2026-02-04T08:30:00Z',
    },
    {
      id: 'usr_pat_005',
      email: 'maria.santos@example.ph',
      role: 'PATIENT',
      is_active: true,
      password_hash: patientPass.hash,
      salt: patientPass.salt,
      created_at: '2026-02-05T09:15:00Z',
      updated_at: '2026-02-05T09:15:00Z',
    },
    {
      id: 'usr_pat_006',
      email: 'gabriel.espeleta@example.ph',
      role: 'PATIENT',
      is_active: true,
      password_hash: patientPass.hash,
      salt: patientPass.salt,
      created_at: '2026-02-06T14:00:00Z',
      updated_at: '2026-02-06T14:00:00Z',
    },
    {
      id: 'usr_pat_007',
      email: 'ana.mendoza@example.ph',
      role: 'PATIENT',
      is_active: true,
      password_hash: patientPass.hash,
      salt: patientPass.salt,
      created_at: '2026-02-07T15:30:00Z',
      updated_at: '2026-02-07T15:30:00Z',
    },
    {
      id: 'usr_pat_008',
      email: 'carlos.alvarez@example.ph',
      role: 'PATIENT',
      is_active: true,
      password_hash: patientPass.hash,
      salt: patientPass.salt,
      created_at: '2026-02-08T16:00:00Z',
      updated_at: '2026-02-08T16:00:00Z',
    },
    {
      id: 'usr_pat_009',
      email: 'daniela.villanueva@example.ph',
      role: 'PATIENT',
      is_active: true,
      password_hash: patientPass.hash,
      salt: patientPass.salt,
      created_at: '2026-02-09T08:00:00Z',
      updated_at: '2026-02-09T08:00:00Z',
    },
    {
      id: 'usr_pat_010',
      email: 'emilio.aguilar@example.ph',
      role: 'PATIENT',
      is_active: true,
      password_hash: patientPass.hash,
      salt: patientPass.salt,
      created_at: '2026-02-10T10:20:00Z',
      updated_at: '2026-02-10T10:20:00Z',
    },
  ];

  // Specializations
  const specializations: Specialization[] = [
    {
      id: 'spec_001',
      name: 'General Medicine',
      description: 'Primary care, physical examinations, and general wellness consultations.',
      created_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'spec_002',
      name: 'Pediatrics',
      description: 'Comprehensive medical care for infants, children, and adolescents.',
      created_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'spec_003',
      name: 'Internal Medicine',
      description: 'Diagnosis, management, and nonsurgical treatment of adult diseases and chronic illness.',
      created_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'spec_004',
      name: 'Family Medicine',
      description: 'Continuous, comprehensive healthcare for individuals and families across all ages.',
      created_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'spec_005',
      name: 'Dermatology',
      description: 'Diagnosis and treatment of skin, hair, nail conditions, and allergic skin reactions.',
      created_at: '2026-01-01T00:00:00Z',
    },
  ];

  // 5 Doctors
  const doctors: Doctor[] = [
    {
      id: 'doc_001',
      user_id: 'usr_doc_001',
      doctor_code: 'DOC-001',
      first_name: 'Maria Lourdes',
      last_name: 'Santos',
      email: 'dr.santos@mediqueue.ph',
      contact_number: '+63 917 123 4567',
      specialization_id: 'spec_003',
      specialization_name: 'Internal Medicine',
      license_number: 'PRC-0089421',
      ptr_number: 'PTR-8921034-MLA',
      s2_license: 'S2-0941208-NCR',
      room_number: 'Room 101',
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'doc_002',
      user_id: 'usr_doc_002',
      doctor_code: 'DOC-002',
      first_name: 'Jose Antonio',
      last_name: 'Reyes',
      email: 'dr.reyes@mediqueue.ph',
      contact_number: '+63 918 234 5678',
      specialization_id: 'spec_002',
      specialization_name: 'Pediatrics',
      license_number: 'PRC-0078319',
      ptr_number: 'PTR-6623910-QC',
      s2_license: 'S2-0881920-NCR',
      room_number: 'Room 102',
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'doc_003',
      user_id: 'usr_doc_003',
      doctor_code: 'DOC-003',
      first_name: 'Carmela Grace',
      last_name: 'Bautista',
      email: 'dr.bautista@mediqueue.ph',
      contact_number: '+63 919 345 6789',
      specialization_id: 'spec_001',
      specialization_name: 'General Medicine',
      license_number: 'PRC-0091244',
      ptr_number: 'PTR-4491028-TAG',
      room_number: 'Room 103',
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'doc_004',
      user_id: 'usr_doc_004',
      doctor_code: 'DOC-004',
      first_name: 'Ramon Vicente',
      last_name: 'Dizon',
      email: 'dr.dizon@mediqueue.ph',
      contact_number: '+63 920 456 7890',
      specialization_id: 'spec_004',
      specialization_name: 'Family Medicine',
      license_number: 'PRC-0065412',
      ptr_number: 'PTR-7729011-PAS',
      room_number: 'Room 104',
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'doc_005',
      user_id: 'usr_doc_005',
      doctor_code: 'DOC-005',
      first_name: 'Angela Cristina',
      last_name: 'Cruz',
      email: 'dr.cruz@mediqueue.ph',
      contact_number: '+63 921 567 8901',
      specialization_id: 'spec_005',
      specialization_name: 'Dermatology',
      license_number: 'PRC-0081930',
      ptr_number: 'PTR-3301982-MAK',
      room_number: 'Room 105',
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
  ];

  // Patients
  const patients: Patient[] = [
    {
      id: 'pat_001',
      user_id: 'usr_pat_001',
      patient_number: 'PAT-2026-001',
      first_name: 'Juan',
      last_name: 'Dela Cruz',
      email: 'juan.delacruz@example.ph',
      contact_number: '+63 917 555 0101',
      date_of_birth: '1992-05-14',
      sex: 'Male',
      address: '124 Rizal Avenue, Batangas City, Batangas',
      emergency_contact_name: 'Clara Dela Cruz (Spouse)',
      emergency_contact_number: '+63 917 555 0102',
      blood_type: 'O+',
      allergies: 'Penicillin',
      is_active: true,
      created_at: '2026-02-01T09:00:00Z',
      updated_at: '2026-02-01T09:00:00Z',
    },
    {
      id: 'pat_002',
      user_id: 'usr_pat_002',
      patient_number: 'PAT-2026-002',
      first_name: 'Bea Patricia',
      last_name: 'Gonzales',
      email: 'bea.gonzales@example.ph',
      contact_number: '+63 918 555 0202',
      date_of_birth: '1998-11-20',
      sex: 'Female',
      address: '45 J.P. Laurel Highway, Lipa City, Batangas',
      emergency_contact_name: 'Roberto Gonzales (Father)',
      emergency_contact_number: '+63 918 555 0203',
      blood_type: 'A+',
      allergies: 'None',
      is_active: true,
      created_at: '2026-02-02T10:00:00Z',
      updated_at: '2026-02-02T10:00:00Z',
    },
    {
      id: 'pat_003',
      user_id: 'usr_pat_003',
      patient_number: 'PAT-2026-003',
      first_name: 'Sofia Isabelle',
      last_name: 'Reyes',
      email: 'sofia.reyes@example.ph',
      contact_number: '+63 919 555 0303',
      date_of_birth: '2019-03-08',
      sex: 'Female',
      address: '88 Mabini St., Tanauan City, Batangas',
      emergency_contact_name: 'Camille Reyes (Mother)',
      emergency_contact_number: '+63 919 555 0304',
      blood_type: 'B+',
      allergies: 'Aspirin',
      is_active: true,
      created_at: '2026-02-03T11:00:00Z',
      updated_at: '2026-02-03T11:00:00Z',
    },
    {
      id: 'pat_004',
      user_id: 'usr_pat_004',
      patient_number: 'PAT-2026-004',
      first_name: 'Joshua Emmanuel',
      last_name: 'Ramos',
      email: 'joshua.ramos@example.ph',
      contact_number: '+63 920 555 0404',
      date_of_birth: '2001-08-17',
      sex: 'Male',
      address: '15 Katipunan Road, Quezon City, Metro Manila',
      emergency_contact_name: 'Elena Ramos (Mother)',
      emergency_contact_number: '+63 920 555 0405',
      blood_type: 'O-',
      allergies: 'Shellfish',
      is_active: true,
      created_at: '2026-02-04T08:30:00Z',
      updated_at: '2026-02-04T08:30:00Z',
    },
    {
      id: 'pat_005',
      user_id: 'usr_pat_005',
      patient_number: 'PAT-2026-005',
      first_name: 'Maria Clara',
      last_name: 'Santos',
      email: 'maria.santos@example.ph',
      contact_number: '+63 921 555 0505',
      date_of_birth: '1985-09-28',
      sex: 'Female',
      address: '23 Commonwealth Ave., Diliman, Quezon City',
      emergency_contact_name: 'Crisostomo Santos (Husband)',
      emergency_contact_number: '+63 921 555 0506',
      blood_type: 'AB+',
      allergies: 'Sulfonamides',
      is_active: true,
      created_at: '2026-02-05T09:15:00Z',
      updated_at: '2026-02-05T09:15:00Z',
    },
    {
      id: 'pat_006',
      user_id: 'usr_pat_006',
      patient_number: 'PAT-2026-006',
      first_name: 'Gabriel',
      last_name: 'Espeleta',
      email: 'gabriel.espeleta@example.ph',
      contact_number: '+63 922 555 0606',
      date_of_birth: '1995-04-12',
      sex: 'Male',
      address: '77 Marawoy, Lipa City, Batangas',
      emergency_contact_name: 'Grace Espeleta (Sister)',
      emergency_contact_number: '+63 922 555 0607',
      blood_type: 'O+',
      allergies: 'None',
      is_active: true,
      created_at: '2026-02-06T14:00:00Z',
      updated_at: '2026-02-06T14:00:00Z',
    },
    {
      id: 'pat_007',
      user_id: 'usr_pat_007',
      patient_number: 'PAT-2026-007',
      first_name: 'Ana',
      last_name: 'Mendoza',
      email: 'ana.mendoza@example.ph',
      contact_number: '+63 923 555 0707',
      date_of_birth: '1990-12-03',
      sex: 'Female',
      address: '102 San Jose St., Pasig City',
      emergency_contact_name: 'Mark Mendoza (Brother)',
      emergency_contact_number: '+63 923 555 0708',
      blood_type: 'A-',
      allergies: 'Dust mites, Pollen',
      is_active: true,
      created_at: '2026-02-07T15:30:00Z',
      updated_at: '2026-02-07T15:30:00Z',
    },
    {
      id: 'pat_008',
      user_id: 'usr_pat_008',
      patient_number: 'PAT-2026-008',
      first_name: 'Carlos',
      last_name: 'Alvarez',
      email: 'carlos.alvarez@example.ph',
      contact_number: '+63 924 555 0808',
      date_of_birth: '1978-06-25',
      sex: 'Male',
      address: '54 Taft Ave., Malate, Manila',
      emergency_contact_name: 'Teresa Alvarez (Wife)',
      emergency_contact_number: '+63 924 555 0809',
      blood_type: 'B-',
      allergies: 'None',
      is_active: true,
      created_at: '2026-02-08T16:00:00Z',
      updated_at: '2026-02-08T16:00:00Z',
    },
    {
      id: 'pat_009',
      user_id: 'usr_pat_009',
      patient_number: 'PAT-2026-009',
      first_name: 'Daniela',
      last_name: 'Villanueva',
      email: 'daniela.villanueva@example.ph',
      contact_number: '+63 925 555 0909',
      date_of_birth: '2003-01-30',
      sex: 'Female',
      address: '32 San Pedro St., San Pablo City, Laguna',
      emergency_contact_name: 'Ramon Villanueva (Father)',
      emergency_contact_number: '+63 925 555 0910',
      blood_type: 'O+',
      allergies: 'NSAIDs',
      is_active: true,
      created_at: '2026-02-09T08:00:00Z',
      updated_at: '2026-02-09T08:00:00Z',
    },
    {
      id: 'pat_010',
      user_id: 'usr_pat_010',
      patient_number: 'PAT-2026-010',
      first_name: 'Emilio',
      last_name: 'Aguilar',
      email: 'emilio.aguilar@example.ph',
      contact_number: '+63 926 555 1010',
      date_of_birth: '1965-02-18',
      sex: 'Male',
      address: '90 General Luna St., Batangas City',
      emergency_contact_name: 'Luzviminda Aguilar (Wife)',
      emergency_contact_number: '+63 926 555 1011',
      blood_type: 'A+',
      allergies: 'Iodine contrast',
      is_active: true,
      created_at: '2026-02-10T10:20:00Z',
      updated_at: '2026-02-10T10:20:00Z',
    },
  ];

  // Doctor Schedules (Monday to Saturday)
  const doctor_schedules: DoctorSchedule[] = [
    // Dr. Santos (Internal Medicine) - Mon, Wed, Fri (08:00 - 12:00, 30 min slots)
    {
      id: 'sch_001',
      doctor_id: 'doc_001',
      day_of_week: 'Monday',
      start_time: '08:00',
      end_time: '12:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'sch_002',
      doctor_id: 'doc_001',
      day_of_week: 'Wednesday',
      start_time: '08:00',
      end_time: '12:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'sch_003',
      doctor_id: 'doc_001',
      day_of_week: 'Friday',
      start_time: '13:00',
      end_time: '17:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    // Dr. Reyes (Pediatrics) - Tue, Thu, Sat (09:00 - 13:00)
    {
      id: 'sch_004',
      doctor_id: 'doc_002',
      day_of_week: 'Tuesday',
      start_time: '09:00',
      end_time: '13:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'sch_005',
      doctor_id: 'doc_002',
      day_of_week: 'Wednesday',
      start_time: '08:00',
      end_time: '12:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'sch_006',
      doctor_id: 'doc_002',
      day_of_week: 'Thursday',
      start_time: '09:00',
      end_time: '13:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'sch_007',
      doctor_id: 'doc_002',
      day_of_week: 'Saturday',
      start_time: '08:00',
      end_time: '12:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    // Dr. Bautista (General Medicine) - Mon to Fri (08:00 - 12:00)
    {
      id: 'sch_008',
      doctor_id: 'doc_003',
      day_of_week: 'Monday',
      start_time: '08:00',
      end_time: '12:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'sch_009',
      doctor_id: 'doc_003',
      day_of_week: 'Wednesday',
      start_time: '08:00',
      end_time: '12:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'sch_010',
      doctor_id: 'doc_003',
      day_of_week: 'Thursday',
      start_time: '08:00',
      end_time: '12:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'sch_011',
      doctor_id: 'doc_003',
      day_of_week: 'Friday',
      start_time: '08:00',
      end_time: '12:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    // Dr. Dizon (Family Medicine) - Tue, Wed, Fri (13:00 - 17:00)
    {
      id: 'sch_012',
      doctor_id: 'doc_004',
      day_of_week: 'Tuesday',
      start_time: '13:00',
      end_time: '17:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'sch_013',
      doctor_id: 'doc_004',
      day_of_week: 'Wednesday',
      start_time: '13:00',
      end_time: '17:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'sch_014',
      doctor_id: 'doc_004',
      day_of_week: 'Friday',
      start_time: '08:00',
      end_time: '12:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    // Dr. Cruz (Dermatology) - Mon, Wed, Thu (10:00 - 15:00)
    {
      id: 'sch_015',
      doctor_id: 'doc_005',
      day_of_week: 'Monday',
      start_time: '10:00',
      end_time: '15:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'sch_016',
      doctor_id: 'doc_005',
      day_of_week: 'Wednesday',
      start_time: '10:00',
      end_time: '15:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
    {
      id: 'sch_017',
      doctor_id: 'doc_005',
      day_of_week: 'Thursday',
      start_time: '10:00',
      end_time: '15:00',
      slot_duration_minutes: 30,
      max_patients_per_slot: 1,
      status: 'Active',
      created_at: '2026-01-05T08:00:00Z',
      updated_at: '2026-01-05T08:00:00Z',
    },
  ];

  // Today's date dynamic or ISO format (e.g. 2026-09-09)
  const today = new Date().toISOString().split('T')[0];

  // Appointments
  const appointments: Appointment[] = [
    // Today's appointments
    {
      id: 'apt_001',
      appointment_reference: 'APT-2026-000101',
      patient_id: 'pat_001',
      doctor_id: 'doc_001',
      schedule_id: 'sch_002',
      appointment_date: today,
      time_slot: '08:00 AM',
      reason_for_consultation: 'Hypertension follow-up and chronic chest tightness evaluation',
      status: 'completed',
      created_at: '2026-09-01T08:30:00Z',
      updated_at: `${today}T08:45:00Z`,
    },
    {
      id: 'apt_002',
      appointment_reference: 'APT-2026-000102',
      patient_id: 'pat_002',
      doctor_id: 'doc_001',
      schedule_id: 'sch_002',
      appointment_date: today,
      time_slot: '08:30 AM',
      reason_for_consultation: 'Recurring migraine headaches and blurred vision episodes',
      status: 'in_consultation',
      created_at: '2026-09-02T09:15:00Z',
      updated_at: `${today}T08:50:00Z`,
    },
    {
      id: 'apt_003',
      appointment_reference: 'APT-2026-000103',
      patient_id: 'pat_003',
      doctor_id: 'doc_002',
      schedule_id: 'sch_005',
      appointment_date: today,
      time_slot: '09:00 AM',
      reason_for_consultation: 'Persistent nocturnal cough and low-grade fever for 3 days',
      status: 'in_queue',
      created_at: '2026-09-03T11:00:00Z',
      updated_at: `${today}T08:55:00Z`,
    },
    {
      id: 'apt_004',
      appointment_reference: 'APT-2026-000104',
      patient_id: 'pat_004',
      doctor_id: 'doc_003',
      schedule_id: 'sch_009',
      appointment_date: today,
      time_slot: '09:30 AM',
      reason_for_consultation: 'Annual physical examination and medical certificate for university clearance',
      status: 'in_queue',
      created_at: '2026-09-04T10:00:00Z',
      updated_at: `${today}T09:05:00Z`,
    },
    {
      id: 'apt_005',
      appointment_reference: 'APT-2026-000105',
      patient_id: 'pat_005',
      doctor_id: 'doc_004',
      schedule_id: 'sch_013',
      appointment_date: today,
      time_slot: '01:00 PM',
      reason_for_consultation: 'Generalized body weakness, joint stiffness, and fatigue',
      status: 'confirmed',
      created_at: '2026-09-05T14:20:00Z',
      updated_at: '2026-09-05T14:20:00Z',
    },
    {
      id: 'apt_006',
      appointment_reference: 'APT-2026-000106',
      patient_id: 'pat_006',
      doctor_id: 'doc_005',
      schedule_id: 'sch_016',
      appointment_date: today,
      time_slot: '10:30 AM',
      reason_for_consultation: 'Itchy erythematous rash on bilateral forearms and neck',
      status: 'confirmed',
      created_at: '2026-09-06T09:40:00Z',
      updated_at: '2026-09-06T09:40:00Z',
    },
    // Future appointments
    {
      id: 'apt_007',
      appointment_reference: 'APT-2026-000107',
      patient_id: 'pat_007',
      doctor_id: 'doc_001',
      schedule_id: 'sch_003',
      appointment_date: '2026-09-11',
      time_slot: '01:30 PM',
      reason_for_consultation: 'Type 2 Diabetes routine HbA1c review and medication adjustment',
      status: 'confirmed',
      created_at: '2026-09-07T08:00:00Z',
      updated_at: '2026-09-07T08:00:00Z',
    },
    {
      id: 'apt_008',
      appointment_reference: 'APT-2026-000108',
      patient_id: 'pat_008',
      doctor_id: 'doc_002',
      schedule_id: 'sch_007',
      appointment_date: '2026-09-12',
      time_slot: '09:00 AM',
      reason_for_consultation: 'Well-child immunization and developmental milestone assessment',
      status: 'pending',
      created_at: '2026-09-08T11:15:00Z',
      updated_at: '2026-09-08T11:15:00Z',
    },
    // Past completed appointment
    {
      id: 'apt_009',
      appointment_reference: 'APT-2026-000089',
      patient_id: 'pat_001',
      doctor_id: 'doc_003',
      schedule_id: 'sch_008',
      appointment_date: '2026-08-25',
      time_slot: '09:00 AM',
      reason_for_consultation: 'Acute productive cough with yellowish phlegm and sore throat',
      status: 'completed',
      created_at: '2026-08-20T10:00:00Z',
      updated_at: '2026-08-25T09:35:00Z',
    },
    {
      id: 'apt_010',
      appointment_reference: 'APT-2026-000090',
      patient_id: 'pat_009',
      doctor_id: 'doc_005',
      schedule_id: 'sch_015',
      appointment_date: '2026-08-28',
      time_slot: '11:00 AM',
      reason_for_consultation: 'Moderate acne vulgaris flare-up on cheeks and forehead',
      status: 'completed',
      created_at: '2026-08-22T13:30:00Z',
      updated_at: '2026-08-28T11:40:00Z',
    },
  ];

  // Today's Queue Items
  const queue: QueueItem[] = [
    {
      id: 'que_001',
      queue_number: 'A001',
      queue_date: today,
      appointment_id: 'apt_001',
      patient_id: 'pat_001',
      doctor_id: 'doc_001',
      check_in_time: `${today}T08:02:00Z`,
      called_time: `${today}T08:10:00Z`,
      consultation_start_time: `${today}T08:12:00Z`,
      completion_time: `${today}T08:42:00Z`,
      status: 'completed',
      remarks: 'Completed consultation with prescription issued.',
      created_at: `${today}T08:02:00Z`,
      updated_at: `${today}T08:42:00Z`,
    },
    {
      id: 'que_002',
      queue_number: 'A002',
      queue_date: today,
      appointment_id: 'apt_002',
      patient_id: 'pat_002',
      doctor_id: 'doc_001',
      check_in_time: `${today}T08:15:00Z`,
      called_time: `${today}T08:45:00Z`,
      consultation_start_time: `${today}T08:48:00Z`,
      status: 'in_consultation',
      remarks: 'Currently inside Room 101 with Dr. Santos.',
      created_at: `${today}T08:15:00Z`,
      updated_at: `${today}T08:48:00Z`,
    },
    {
      id: 'que_003',
      queue_number: 'A003',
      queue_date: today,
      appointment_id: 'apt_003',
      patient_id: 'pat_003',
      doctor_id: 'doc_002',
      check_in_time: `${today}T08:40:00Z`,
      called_time: `${today}T09:05:00Z`,
      status: 'called',
      remarks: 'Called to proceed to Room 102 (Pediatrics).',
      created_at: `${today}T08:40:00Z`,
      updated_at: `${today}T09:05:00Z`,
    },
    {
      id: 'que_004',
      queue_number: 'A004',
      queue_date: today,
      appointment_id: 'apt_004',
      patient_id: 'pat_004',
      doctor_id: 'doc_003',
      check_in_time: `${today}T08:55:00Z`,
      status: 'waiting',
      remarks: 'Seated in Main Waiting Area.',
      created_at: `${today}T08:55:00Z`,
      updated_at: `${today}T08:55:00Z`,
    },
  ];

  // Consultations
  const consultations: Consultation[] = [
    {
      id: 'con_001',
      appointment_id: 'apt_001',
      patient_id: 'pat_001',
      doctor_id: 'doc_001',
      chief_complaint: 'Follow-up for elevated blood pressure readings (145/95 mmHg) and intermittent occipital headaches.',
      symptoms: 'Morning headaches, mild dizziness when standing quickly, occasional palpitations. No chest pain or syncope.',
      diagnosis: 'Essential Hypertension Stage 1 (Poorly Controlled on monotherapy); Tension-type Headache secondary to stress.',
      clinical_notes: 'BP: 142/92 mmHg, PR: 78 bpm, RR: 18 cpm, Temp: 36.6°C. Heart sounds S1/S2 distinct, no murmurs. Lungs clear to auscultation.',
      prescription: '1. Losartan Potassium 50 mg tablet - Take 1 tablet once daily in the morning.\n2. Amlodipine Besylate 5 mg tablet - Take 1 tablet once daily in the evening.\n3. Paracetamol 500 mg tablet - Take 1 tablet every 6 hours as needed for headache.',
      recommendations: 'Adopt DASH diet (low sodium <2g/day, high fiber). Daily home BP monitoring in the morning and before sleep. Moderate aerobic exercise 30 mins/day 5x a week. Avoid caffeine and smoking.',
      follow_up_date: '2026-09-23',
      consultation_date: today,
      is_locked: true,
      signed_at: `${today}T08:40:00Z`,
      created_at: `${today}T08:40:00Z`,
      updated_at: `${today}T08:40:00Z`,
    },
    {
      id: 'con_002',
      appointment_id: 'apt_009',
      patient_id: 'pat_001',
      doctor_id: 'doc_003',
      chief_complaint: '5-day history of productive cough, mild sore throat, and nasal congestion.',
      symptoms: 'Yellowish sputum, low-grade fever up to 37.9°C two nights ago, malaise, throat tickle.',
      diagnosis: 'Acute Bronchitis (Presumed Viral with Secondary Bacterial Infection); Acute Rhinosinusitis.',
      clinical_notes: 'Oropharynx: mildly erythematous, no tonsillar exudates. Chest: coarse rhonchi bilaterally, clearing after voluntary cough. No wheezes.',
      prescription: '1. Amoxicillin + Clavulanic Acid (Co-Amoxiclav) 625 mg tablet - Take 1 tablet every 12 hours after meals for 7 days.\n2. Carbocisteine 500 mg capsule - Take 1 capsule 3 times a day for 5 days.\n3. Cetirizine HCl 10 mg tablet - Take 1 tablet at bedtime for 5 days.',
      recommendations: 'Increase oral fluid intake to 2.5-3 liters per day. Warm saline gargles 3 times daily. Adequate rest and steam inhalation.',
      follow_up_date: '2026-09-02',
      consultation_date: '2026-08-25',
      is_locked: true,
      signed_at: '2026-08-25T09:30:00Z',
      created_at: '2026-08-25T09:30:00Z',
      updated_at: '2026-08-25T09:30:00Z',
    },
    {
      id: 'con_003',
      appointment_id: 'apt_010',
      patient_id: 'pat_009',
      doctor_id: 'doc_005',
      chief_complaint: 'Facial breakout with painful red bumps and pustules for the past 3 weeks.',
      symptoms: 'Multiple inflammatory papules and pustules over bilateral cheeks and chin. Mild tenderness.',
      diagnosis: 'Acne Vulgaris, Moderate Inflammatory Papulopustular Type.',
      clinical_notes: 'Skin examination reveals erythematous papules (15-20) and small pustules with scattered open and closed comedones. No deep cystic nodules.',
      prescription: '1. Clindamycin 1% topical gel - Apply thin layer to affected areas twice daily.\n2. Benzoyl Peroxide 2.5% wash - Use once daily as facial cleanser in the morning.\n3. Doxycycline 100 mg capsule - Take 1 capsule once daily with a full glass of water for 30 days.',
      recommendations: 'Use gentle non-comedogenic foaming cleanser and water-based sunscreen (SPF 50). Avoid picking or squeezing lesions. Limit dairy and high-glycemic foods.',
      follow_up_date: '2026-09-28',
      consultation_date: '2026-08-28',
      is_locked: true,
      signed_at: '2026-08-28T11:35:00Z',
      created_at: '2026-08-28T11:35:00Z',
      updated_at: '2026-08-28T11:35:00Z',
    },
  ];

  // Audit Logs
  const audit_logs: AuditLog[] = [
    {
      id: 'aud_001',
      user_id: 'usr_admin_001',
      user_email: 'admin@mediqueue.ph',
      user_role: 'ADMIN',
      action: 'System Initialized',
      module: 'Settings',
      record_id: 'cli_001',
      details: 'MediQueue Clinic Management System configured with operating hours 08:00 - 17:00.',
      timestamp: '2026-09-01T08:00:00Z',
    },
    {
      id: 'aud_002',
      user_id: 'usr_admin_001',
      user_email: 'admin@mediqueue.ph',
      user_role: 'ADMIN',
      action: 'Created Doctor Schedule',
      module: 'Schedules',
      record_id: 'sch_001',
      details: 'Assigned Dr. Maria Lourdes Santos to Monday 08:00 - 12:00 in Room 101.',
      timestamp: '2026-09-01T08:15:00Z',
    },
    {
      id: 'aud_003',
      user_id: 'usr_pat_001',
      user_email: 'juan.delacruz@example.ph',
      user_role: 'PATIENT',
      action: 'Booked Appointment',
      module: 'Appointments',
      record_id: 'apt_001',
      details: 'Patient booked appointment reference APT-2026-000101 with Dr. Santos for 08:00 AM.',
      timestamp: '2026-09-01T08:30:00Z',
    },
    {
      id: 'aud_004',
      user_id: 'usr_admin_001',
      user_email: 'admin@mediqueue.ph',
      user_role: 'ADMIN',
      action: 'Checked In Patient',
      module: 'Queue',
      record_id: 'que_001',
      details: 'Checked in Juan Dela Cruz (APT-2026-000101), generated queue number A001.',
      timestamp: `${today}T08:02:00Z`,
    },
    {
      id: 'aud_005',
      user_id: 'usr_doc_001',
      user_email: 'dr.santos@mediqueue.ph',
      user_role: 'DOCTOR',
      action: 'Called Patient',
      module: 'Queue',
      record_id: 'que_001',
      details: 'Dr. Santos called queue number A001 (Juan Dela Cruz) into Room 101.',
      timestamp: `${today}T08:10:00Z`,
    },
    {
      id: 'aud_006',
      user_id: 'usr_doc_001',
      user_email: 'dr.santos@mediqueue.ph',
      user_role: 'DOCTOR',
      action: 'Completed Consultation',
      module: 'Consultations',
      record_id: 'con_001',
      details: 'Dr. Santos completed consultation for Juan Dela Cruz. Diagnosis: Essential Hypertension.',
      timestamp: `${today}T08:42:00Z`,
    },
    {
      id: 'aud_007',
      user_id: 'usr_admin_001',
      user_email: 'admin@mediqueue.ph',
      user_role: 'ADMIN',
      action: 'Checked In Patient',
      module: 'Queue',
      record_id: 'que_002',
      details: 'Checked in Bea Patricia Gonzales (APT-2026-000102), generated queue number A002.',
      timestamp: `${today}T08:15:00Z`,
    },
    {
      id: 'aud_008',
      user_id: 'usr_doc_001',
      user_email: 'dr.santos@mediqueue.ph',
      user_role: 'DOCTOR',
      action: 'Started Consultation',
      module: 'Queue',
      record_id: 'que_002',
      details: 'Dr. Santos started consultation for Bea Patricia Gonzales (Queue A002).',
      timestamp: `${today}T08:48:00Z`,
    },
    {
      id: 'aud_009',
      user_id: 'usr_admin_001',
      user_email: 'admin@mediqueue.ph',
      user_role: 'ADMIN',
      action: 'Checked In Patient',
      module: 'Queue',
      record_id: 'que_003',
      details: 'Checked in Sofia Isabelle Reyes (APT-2026-000103), generated queue number A003.',
      timestamp: `${today}T08:40:00Z`,
    },
    {
      id: 'aud_010',
      user_id: 'usr_doc_002',
      user_email: 'dr.reyes@mediqueue.ph',
      user_role: 'DOCTOR',
      action: 'Called Patient',
      module: 'Queue',
      record_id: 'que_003',
      details: 'Dr. Reyes called queue number A003 into Room 102.',
      timestamp: `${today}T09:05:00Z`,
    },
  ];

  // Clinic Settings
  const clinic_settings: ClinicSettings = {
    id: 'cli_001',
    clinic_name: 'MediQueue Healthcare Center',
    tagline: 'Modern Community & School Health Services',
    contact_number: '+63 43 756 1234 / +63 917 800 5000',
    email: 'info@mediqueue.ph',
    address: '100 Medical Plaza, Ayala Highway, Lipa City, Batangas 4217',
    operating_days: 'Monday to Saturday',
    opening_time: '08:00',
    closing_time: '17:00',
    daily_queue_prefix: 'A',
    avg_consultation_time_minutes: 20,
    emergency_contact: 'Batangas Emergency Hotline: 911 / (043) 723-1234',
    updated_at: '2026-09-01T08:00:00Z',
  };

  // Initial Notifications
  const notifications: Notification[] = [
    {
      id: 'notif_001',
      user_id: 'usr_pat_001',
      title: 'Consultation Completed',
      message: 'Your consultation with Dr. Maria Lourdes Santos has been completed. Check your consultation record and prescription.',
      type: 'consultation',
      is_read: true,
      created_at: `${today}T08:42:00Z`,
    },
    {
      id: 'notif_002',
      user_id: 'usr_pat_002',
      title: 'Consultation in Progress',
      message: 'You are currently in consultation with Dr. Maria Lourdes Santos in Room 101.',
      type: 'queue',
      is_read: false,
      created_at: `${today}T08:48:00Z`,
    },
    {
      id: 'notif_003',
      user_id: 'usr_pat_003',
      title: 'Queue Called',
      message: 'Queue A003 is now being called! Please proceed immediately to Room 102 (Pediatrics) with Dr. Jose Antonio Reyes.',
      type: 'queue',
      is_read: false,
      created_at: `${today}T09:05:00Z`,
    },
    {
      id: 'notif_004',
      user_id: 'usr_pat_004',
      title: 'Checked In Successfully',
      message: 'You are checked in! Your queue number is A004. Please relax in the waiting lounge until your number is announced.',
      type: 'queue',
      is_read: false,
      created_at: `${today}T08:55:00Z`,
    },
  ];

  // Vital Signs History Seeds (Multiple records over time for trend charts)
  const vital_signs: VitalSignRecord[] = [
    {
      id: 'vtl_001',
      patient_id: 'pat_001',
      recorded_at: '2026-02-10T09:15:00Z',
      systolic_bp: 138,
      diastolic_bp: 88,
      heart_rate: 82,
      temperature_c: 36.6,
      respiratory_rate: 18,
      spo2: 98,
      blood_glucose_mgdl: 110,
      weight_kg: 76.5,
      height_cm: 172,
      bmi: 25.9,
      notes: 'Initial consultation vitals. Borderline pre-hypertension.',
      recorded_by_name: 'Nurse Joy Cruz',
      recorded_by_role: 'Nurse',
    },
    {
      id: 'vtl_002',
      patient_id: 'pat_001',
      recorded_at: '2026-03-05T10:00:00Z',
      systolic_bp: 130,
      diastolic_bp: 84,
      heart_rate: 76,
      temperature_c: 36.5,
      respiratory_rate: 16,
      spo2: 99,
      blood_glucose_mgdl: 102,
      weight_kg: 75.0,
      height_cm: 172,
      bmi: 25.4,
      notes: 'Follow up check. Blood pressure improving with lifestyle adjustment.',
      recorded_by_name: 'Dr. Maria Santos',
      recorded_by_role: 'Doctor',
    },
    {
      id: 'vtl_003',
      patient_id: 'pat_001',
      recorded_at: `${today}T08:30:00Z`,
      systolic_bp: 124,
      diastolic_bp: 80,
      heart_rate: 72,
      temperature_c: 36.7,
      respiratory_rate: 16,
      spo2: 99,
      blood_glucose_mgdl: 96,
      weight_kg: 74.2,
      height_cm: 172,
      bmi: 25.1,
      notes: 'Current clinic visit. Normotensive, stable vitals.',
      recorded_by_name: 'Nurse Joy Cruz',
      recorded_by_role: 'Triage',
    },
    {
      id: 'vtl_004',
      patient_id: 'pat_002',
      recorded_at: '2026-01-20T14:10:00Z',
      systolic_bp: 118,
      diastolic_bp: 76,
      heart_rate: 74,
      temperature_c: 36.8,
      spo2: 98,
      blood_glucose_mgdl: 92,
      weight_kg: 58.0,
      height_cm: 160,
      bmi: 22.7,
      notes: 'Annual physical exam check.',
      recorded_by_name: 'Nurse Joy Cruz',
      recorded_by_role: 'Nurse',
    },
    {
      id: 'vtl_005',
      patient_id: 'pat_002',
      recorded_at: `${today}T08:45:00Z`,
      systolic_bp: 115,
      diastolic_bp: 75,
      heart_rate: 78,
      temperature_c: 37.9,
      spo2: 97,
      blood_glucose_mgdl: 95,
      weight_kg: 57.5,
      height_cm: 160,
      bmi: 22.5,
      notes: 'Mild febrile state with productive cough.',
      recorded_by_name: 'Dr. Jose Antonio Reyes',
      recorded_by_role: 'Doctor',
    },
  ];

  // Lab Orders Seeds
  const lab_orders: LabOrder[] = [
    {
      id: 'lab_001',
      order_number: 'LAB-2026-00101',
      patient_id: 'pat_001',
      doctor_id: 'doc_001',
      consultation_id: 'cns_001',
      status: 'completed',
      priority: 'Routine',
      clinical_indication: 'Evaluation for essential hypertension & lipid screening',
      fasting_required: true,
      specimen_notes: '10-12 hours fasting required before morning venous draw',
      results_summary: 'Total Cholesterol: 198 mg/dL (Normal). Fasting Blood Sugar: 96 mg/dL. Creatinine: 0.9 mg/dL.',
      created_at: '2026-02-10T10:00:00Z',
      updated_at: '2026-02-12T14:30:00Z',
      tests: [
        {
          id: 'tst_001',
          test_code: 'LIP-01',
          test_name: 'Lipid Profile (Total, HDL, LDL, Triglycerides)',
          category: 'Clinical Chemistry',
          standard_price: 850,
          fasting_required: true,
          estimated_turnaround_hours: 24,
        },
        {
          id: 'tst_002',
          test_code: 'FBS-01',
          test_name: 'Fasting Blood Sugar (FBS)',
          category: 'Clinical Chemistry',
          standard_price: 250,
          fasting_required: true,
          estimated_turnaround_hours: 12,
        },
      ],
    },
    {
      id: 'lab_002',
      order_number: 'LAB-2026-00102',
      patient_id: 'pat_002',
      doctor_id: 'doc_002',
      status: 'pending',
      priority: 'Urgent',
      clinical_indication: 'Persistent cough and fever for 4 days, rule out bronchopneumonia',
      fasting_required: false,
      specimen_notes: 'Standard PA chest radiograph. Complete blood count with platelet count.',
      created_at: `${today}T09:10:00Z`,
      updated_at: `${today}T09:10:00Z`,
      tests: [
        {
          id: 'tst_003',
          test_code: 'CXR-PA',
          test_name: 'Chest X-Ray (PA View)',
          category: 'Imaging & Radiology',
          standard_price: 650,
          fasting_required: false,
          estimated_turnaround_hours: 4,
          preparation_instructions: 'Remove metallic accessories and jewelry prior to chest imaging',
        },
        {
          id: 'tst_004',
          test_code: 'CBC-PLT',
          test_name: 'Complete Blood Count (CBC) with Platelet Count',
          category: 'Hematology',
          standard_price: 400,
          fasting_required: false,
          estimated_turnaround_hours: 2,
        },
      ],
    },
  ];

  // Billing & Invoicing Seeds
  const billing_invoices: BillingInvoice[] = [
    {
      id: 'inv_001',
      invoice_number: 'INV-2026-00891',
      patient_id: 'pat_001',
      doctor_id: 'doc_001',
      appointment_id: 'apt_001',
      queue_item_id: 'q_001',
      items: [
        {
          id: 'itm_001',
          description: 'Specialist Consultation Fee (Internal Medicine)',
          category: 'consultation',
          quantity: 1,
          unit_price: 800,
          total: 800,
        },
        {
          id: 'itm_002',
          description: 'Lipid Profile + Fasting Blood Sugar Lab Diagnostic',
          category: 'laboratory',
          quantity: 1,
          unit_price: 1100,
          total: 1100,
        },
      ],
      subtotal: 1900,
      discount_amount: 0,
      discount_type: 'None',
      tax_amount: 0,
      total_amount: 1900,
      status: 'paid',
      payment_method: 'hmo',
      amount_paid: 1900,
      balance_due: 0,
      hmo_provider: 'Maxicare Healthcare',
      hmo_member_id: 'MAX-882910381',
      hmo_approval_code: 'APV-MAX-9921',
      hmo_coverage_amount: 1900,
      patient_copay: 0,
      cashier_name: 'Admin Sarah Connor',
      payment_date: '2026-02-10T10:45:00Z',
      receipt_number: 'OR-2026-00441',
      remarks: 'HMO Full Approval Letter verified.',
      created_at: '2026-02-10T10:20:00Z',
      updated_at: '2026-02-10T10:45:00Z',
    },
    {
      id: 'inv_002',
      invoice_number: 'INV-2026-00892',
      patient_id: 'pat_002',
      doctor_id: 'doc_002',
      appointment_id: 'apt_002',
      queue_item_id: 'q_002',
      items: [
        {
          id: 'itm_003',
          description: 'Pediatric Specialty Consultation',
          category: 'consultation',
          quantity: 1,
          unit_price: 700,
          total: 700,
        },
        {
          id: 'itm_004',
          description: 'Chest X-Ray PA & CBC Diagnostic Request',
          category: 'laboratory',
          quantity: 1,
          unit_price: 1050,
          total: 1050,
        },
      ],
      subtotal: 1750,
      discount_amount: 0,
      discount_type: 'None',
      tax_amount: 0,
      total_amount: 1750,
      status: 'pending',
      amount_paid: 0,
      balance_due: 1750,
      cashier_name: 'Admin Sarah Connor',
      remarks: 'Pending payment at billing counter.',
      created_at: `${today}T09:15:00Z`,
      updated_at: `${today}T09:15:00Z`,
    },
    {
      id: 'inv_003',
      invoice_number: 'INV-2026-00893',
      patient_id: 'pat_003',
      doctor_id: 'doc_001',
      items: [
        {
          id: 'itm_005',
          description: 'Senior Outpatient General Consultation',
          category: 'consultation',
          quantity: 1,
          unit_price: 600,
          total: 600,
        },
      ],
      subtotal: 600,
      discount_amount: 120,
      discount_type: 'Senior Citizen (20%)',
      tax_amount: 0,
      total_amount: 480,
      status: 'paid',
      payment_method: 'cash',
      amount_paid: 500,
      change_amount: 20,
      balance_due: 0,
      cashier_name: 'Admin Sarah Connor',
      payment_date: `${today}T08:50:00Z`,
      receipt_number: 'OR-2026-00442',
      remarks: 'OSCA ID # 2018-9921 validated.',
      created_at: `${today}T08:40:00Z`,
      updated_at: `${today}T08:50:00Z`,
    },
  ];

  // Doctor Work Statuses (Real-time availability & break status)
  const doctor_work_statuses: DoctorWorkStatus[] = [
    {
      doctor_id: 'doc_001',
      status: 'in_consultation',
      status_message: 'In active consultation with Ticket A001',
      updated_at: `${today}T09:00:00Z`,
    },
    {
      doctor_id: 'doc_002',
      status: 'available',
      status_message: 'Room 102 open for next patient',
      updated_at: `${today}T09:05:00Z`,
    },
    {
      doctor_id: 'doc_003',
      status: 'on_break',
      status_message: '15-minute quick clinical recess',
      break_minutes_remaining: 12,
      updated_at: `${today}T09:10:00Z`,
    },
    {
      doctor_id: 'doc_004',
      status: 'available',
      status_message: 'Room 201 open for dermatology consultation',
      updated_at: `${today}T08:30:00Z`,
    },
    {
      doctor_id: 'doc_005',
      status: 'available',
      status_message: 'Room 202 open for general checkups',
      updated_at: `${today}T08:30:00Z`,
    },
  ];

  // Pre-Consultation Triage Intake Seeds
  const triages: PreConsultationTriage[] = [
    {
      id: 'trg_001',
      appointment_id: 'apt_001',
      patient_id: 'pat_001',
      chief_complaint: 'Occasional morning dizziness and slight palpitations',
      symptoms_duration: '3 weeks on and off',
      pain_scale: 2,
      current_medications: 'Amlodipine 5mg once daily',
      known_allergies: 'Penicillin (mild skin rash)',
      medical_history_notes: 'Stage 1 essential hypertension diagnosed 2024. Non-smoker.',
      vitals_snapshot: {
        blood_pressure: '124/80',
        temperature_c: 36.7,
        heart_rate: 72,
        spo2: 99,
      },
      submitted_at: `${today}T08:20:00Z`,
    },
  ];

  // Pharmacy & Formulary Inventory Seeds
  const pharmacy_items: PharmacyItem[] = [
    {
      id: 'med_001',
      medicine_name: 'Amoxicillin 500mg',
      generic_name: 'Amoxicillin Trihydrate',
      dosage_form: 'Capsule',
      strength: '500mg',
      unit_price: 18.0,
      stock_quantity: 450,
      reorder_level: 100,
      expiration_date: '2027-08-30',
      batch_number: 'AMX-2025-99A',
      manufacturer: 'Unilab Philippines',
      is_active: true,
    },
    {
      id: 'med_002',
      medicine_name: 'Amlodipine Besylate 5mg',
      generic_name: 'Amlodipine',
      dosage_form: 'Tablet',
      strength: '5mg',
      unit_price: 12.5,
      stock_quantity: 620,
      reorder_level: 150,
      expiration_date: '2028-01-15',
      batch_number: 'AML-2025-04B',
      manufacturer: 'Pfizer / Generic',
      is_active: true,
    },
    {
      id: 'med_003',
      medicine_name: 'Metformin HCl 500mg',
      generic_name: 'Metformin Hydrochloride',
      dosage_form: 'Tablet',
      strength: '500mg',
      unit_price: 9.75,
      stock_quantity: 580,
      reorder_level: 120,
      expiration_date: '2027-11-20',
      batch_number: 'MET-2025-11X',
      manufacturer: 'Ritemed',
      is_active: true,
    },
    {
      id: 'med_004',
      medicine_name: 'Paracetamol 500mg',
      generic_name: 'Acetaminophen',
      dosage_form: 'Tablet',
      strength: '500mg',
      unit_price: 6.0,
      stock_quantity: 1200,
      reorder_level: 250,
      expiration_date: '2028-06-30',
      batch_number: 'PCM-2025-77R',
      manufacturer: 'Biogesic / Unilab',
      is_active: true,
    },
    {
      id: 'med_005',
      medicine_name: 'Salbutamol Inhaler 100mcg',
      generic_name: 'Albuterol Sulfate',
      dosage_form: 'Inhaler',
      strength: '100mcg/dose',
      unit_price: 340.0,
      stock_quantity: 35,
      reorder_level: 20,
      expiration_date: '2027-04-10',
      batch_number: 'SAL-2024-88P',
      manufacturer: 'GlaxoSmithKline',
      is_active: true,
    },
    {
      id: 'med_006',
      medicine_name: 'Losartan Potassium 50mg',
      generic_name: 'Losartan',
      dosage_form: 'Tablet',
      strength: '50mg',
      unit_price: 15.0,
      stock_quantity: 420,
      reorder_level: 100,
      expiration_date: '2027-09-18',
      batch_number: 'LOS-2025-02Z',
      manufacturer: 'Therapharma',
      is_active: true,
    },
  ];

  // Prescription Dispensing Seeds
  const dispense_records: PrescriptionDispense[] = [
    {
      id: 'dsp_001',
      consultation_id: 'cns_001',
      patient_id: 'pat_001',
      doctor_id: 'doc_001',
      prescription_text: 'Amlodipine 5mg 1 tab once daily in morning. Paracetamol 500mg 1 tab PRN for headache.',
      items: [
        {
          pharmacy_item_id: 'med_002',
          medicine_name: 'Amlodipine Besylate 5mg',
          dosage_instructions: 'Take 1 tablet by mouth every morning with water',
          quantity: 30,
          unit_price: 12.5,
          total_price: 375.0,
        },
        {
          pharmacy_item_id: 'med_004',
          medicine_name: 'Paracetamol 500mg',
          dosage_instructions: 'Take 1 tablet every 4-6 hours as needed for headache',
          quantity: 10,
          unit_price: 6.0,
          total_price: 60.0,
        },
      ],
      status: 'prepared',
      counseling_notes: 'Monitor blood pressure weekly. Report any swelling in lower ankles.',
      dispensed_by: 'Pharm. Elena Ramos, RPh',
      created_at: `${today}T09:45:00Z`,
    },
  ];

  // Diagnostic Lab Results Seeds
  const lab_results: LabTestResult[] = [
    {
      id: 'lres_001',
      lab_order_id: 'ord_001',
      patient_id: 'pat_001',
      doctor_id: 'doc_001',
      test_name: 'Complete Blood Count (CBC)',
      category: 'Hematology',
      sample_drawn_at: `${today}T07:45:00Z`,
      performed_by: 'Mark Bautista, RMT (Medical Technologist)',
      verified_by: 'Dr. Roberto Gomez, MD, FPSP (Pathologist)',
      result_date: `${today}T09:15:00Z`,
      status: 'released',
      clinical_interpretation: 'CBC findings are within normal physiological baseline. No leukocytosis or acute infection noted.',
      parameters: [
        {
          parameter_name: 'Hemoglobin',
          value: 14.8,
          unit: 'g/dL',
          reference_range: '13.0 - 17.5',
          flag: 'normal',
        },
        {
          parameter_name: 'Hematocrit',
          value: 43.5,
          unit: '%',
          reference_range: '40.0 - 52.0',
          flag: 'normal',
        },
        {
          parameter_name: 'White Blood Cell (WBC)',
          value: 7.2,
          unit: 'x10^9/L',
          reference_range: '4.5 - 11.0',
          flag: 'normal',
        },
        {
          parameter_name: 'Platelet Count',
          value: 260,
          unit: 'x10^9/L',
          reference_range: '150 - 450',
          flag: 'normal',
        },
        {
          parameter_name: 'Neutrophils',
          value: 58,
          unit: '%',
          reference_range: '50 - 70',
          flag: 'normal',
        },
        {
          parameter_name: 'Lymphocytes',
          value: 34,
          unit: '%',
          reference_range: '20 - 40',
          flag: 'normal',
        },
      ],
      created_at: `${today}T09:15:00Z`,
    },
    {
      id: 'lres_002',
      lab_order_id: 'ord_001',
      patient_id: 'pat_001',
      doctor_id: 'doc_001',
      test_name: 'Fasting Blood Sugar (FBS)',
      category: 'Clinical Chemistry',
      sample_drawn_at: `${today}T07:45:00Z`,
      performed_by: 'Mark Bautista, RMT',
      verified_by: 'Dr. Roberto Gomez, MD, FPSP',
      result_date: `${today}T09:30:00Z`,
      status: 'released',
      clinical_interpretation: 'Normal fasting blood glucose. No evidence of impaired fasting glycemia.',
      parameters: [
        {
          parameter_name: 'Glucose (Fasting)',
          value: 92,
          unit: 'mg/dL',
          reference_range: '70 - 99',
          flag: 'normal',
        },
      ],
      created_at: `${today}T09:30:00Z`,
    },
  ];

  // Automated SMS & Queue Notification Logs
  const sms_logs: SmsLog[] = [
    {
      id: 'sms_001',
      recipient_phone: '+63 917 123 4567',
      recipient_name: 'Juan Dela Cruz',
      message: 'MediQueue: Your appointment with Dr. Santos is today at 9:00 AM (Ref: APT-2026-0001). Please arrive 15 mins before.',
      type: 'appointment_reminder',
      status: 'delivered',
      sent_at: `${today}T06:30:00Z`,
    },
    {
      id: 'sms_002',
      recipient_phone: '+63 917 123 4567',
      recipient_name: 'Juan Dela Cruz',
      message: 'MediQueue ALERT: You are next in line! Ticket #A001. Please proceed to Consultation Room 101.',
      type: 'queue_proximity',
      status: 'delivered',
      sent_at: `${today}T08:58:00Z`,
    },
  ];

  // Telemedicine Sessions
  const telemed_sessions: TelemedSession[] = [
    {
      id: 'tel_001',
      appointment_id: 'apt_001',
      patient_id: 'pat_001',
      doctor_id: 'doc_001',
      room_code: 'MEDIQUEUE-TEL-9981',
      status: 'scheduled',
      doctor_notes: 'Follow-up on blood pressure control and lipid monitoring.',
    },
  ];

  // Clinic Satellite Branches
  const clinic_branches: ClinicBranch[] = [
    {
      id: 'brn_001',
      branch_code: 'MNL-CENTRAL',
      name: 'MediQueue Central Medical Center',
      address: 'Suite 401, MediTower, Taft Ave, Ermita',
      city: 'Manila',
      contact_number: '+63 (02) 8524-1000',
      email: 'central@mediqueue.ph',
      operating_hours: 'Monday - Saturday: 7:00 AM - 7:00 PM',
      is_active: true,
    },
    {
      id: 'brn_002',
      branch_code: 'BGC-HUB',
      name: 'MediQueue BGC Health & Diagnostic Hub',
      address: 'Level 2, Bonifacio One, 28th St, BGC',
      city: 'Taguig',
      contact_number: '+63 (02) 8888-2424',
      email: 'bgc@mediqueue.ph',
      operating_hours: 'Monday - Sunday: 8:00 AM - 8:00 PM',
      is_active: true,
    },
    {
      id: 'brn_003',
      branch_code: 'ALB-SAT',
      name: 'MediQueue Alabang Outpatient Clinic',
      address: 'Commerce Ave corner Spectrum Midway, Filinvest',
      city: 'Muntinlupa',
      contact_number: '+63 (02) 8771-3300',
      email: 'alabang@mediqueue.ph',
      operating_hours: 'Monday - Friday: 8:00 AM - 5:00 PM',
      is_active: true,
    },
  ];

  // -------------------------------------------------------------
  // SEED: DIGITAL MEDICAL CERTIFICATES & CLEARANCES
  // -------------------------------------------------------------
  const medical_certificates: MedicalCertificate[] = [
    {
      id: 'mc_001',
      certificate_number: 'MC-2026-00481',
      patient_id: 'pat_002', // Bea Gonzales
      doctor_id: 'doc_001', // Dr. Santos
      consultation_id: 'cns_002',
      certificate_type: 'sick_leave',
      title: 'Medical Certificate — Temporary Incapacity & Sick Leave',
      diagnosis: 'Acute Bronchitis with Moderate Wheezing',
      icd10_code: 'J20.9',
      findings_summary: 'Patient presented with productive cough, mild dyspnea, and low-grade pyrexia. Chest auscultation revealed bilateral coarse crackles. Vital signs stabilized after bronchodilator nebulization.',
      recommendations: 'Advised strict home bed rest, oral hydration (>2.5L/day), and completion of oral antibiotic regimen. Excuse from all academic and occupational duties for three (3) days.',
      rest_days: 3,
      effective_date: '2026-09-08',
      expiry_date: '2026-09-11',
      physician_credentials: {
        name: 'Dr. Maria Lourdes Santos, MD, FPCP',
        specialization: 'Internal Medicine',
        prc_license: 'PRC-0089421',
        ptr_number: 'PTR-8921034-MLA',
        s2_license: 'S2-0941208-NCR',
      },
      qr_verification_code: 'VERIFY-MC-90214',
      verification_hash: 'sha256-e91b8a4f9011',
      remarks: 'Issued for official employer / HR health excuse clearance.',
      is_valid: true,
      created_at: '2026-09-08T11:15:00Z',
    },
    {
      id: 'mc_002',
      certificate_number: 'MC-2026-00482',
      patient_id: 'pat_001', // Juan Dela Cruz
      doctor_id: 'doc_003', // Dr. Bautista
      consultation_id: 'cns_001',
      certificate_type: 'fit_to_work',
      title: 'Official Medical Certificate — Fit to Work Clearance',
      diagnosis: 'Resolved Acute Gastroenteritis with Mild Dehydration',
      icd10_code: 'K52.9',
      findings_summary: 'Patient is asymptomatic for the past 48 hours. Tolerating regular solid diet, afebrile, normotensive, with benign abdominal exam and normal bowel sounds.',
      recommendations: 'Patient is certified medically and physically fit to resume full employment duties, desk operations, and regular occupational tasks without work restrictions.',
      rest_days: 0,
      effective_date: '2026-09-09',
      expiry_date: '2026-12-09',
      physician_credentials: {
        name: 'Dr. Carmela Grace Bautista, MD',
        specialization: 'General Medicine',
        prc_license: 'PRC-0091244',
        ptr_number: 'PTR-4491028-TAG',
      },
      qr_verification_code: 'VERIFY-MC-81092',
      verification_hash: 'sha256-a482b1c81092',
      remarks: 'Certified Fit to Work following medical re-evaluation.',
      is_valid: true,
      created_at: '2026-09-09T14:30:00Z',
    },
    {
      id: 'mc_003',
      certificate_number: 'MC-2026-00483',
      patient_id: 'pat_003', // Sofia Reyes
      doctor_id: 'doc_002', // Dr. Reyes
      consultation_id: 'cns_003',
      certificate_type: 'student_clearance',
      title: 'Pediatric Student Health & Physical Education Clearance',
      diagnosis: 'Healthy Physical Examination — Normal Growth & Development',
      icd10_code: 'Z00.129',
      findings_summary: 'Comprehensive pediatric wellness screening. Visual acuity, cardiopulmonary auscultation, and musculoskeletal range of motion all within normal developmental parameters.',
      recommendations: 'Cleared for unrestricted participation in academic classroom activities, varsity athletics, swimming, and physical education classes for School Year 2026-2027.',
      rest_days: 0,
      effective_date: '2026-09-05',
      expiry_date: '2027-05-31',
      physician_credentials: {
        name: 'Dr. Jose Antonio Reyes, MD, FPPS',
        specialization: 'Pediatrics',
        prc_license: 'PRC-0078319',
        ptr_number: 'PTR-6623910-QC',
        s2_license: 'S2-0881920-NCR',
      },
      qr_verification_code: 'VERIFY-MC-74199',
      verification_hash: 'sha256-f559c1174199',
      remarks: 'Annual school health evaluation clearance.',
      is_valid: true,
      created_at: '2026-09-05T09:45:00Z',
    },
  ];

  // -------------------------------------------------------------
  // SEED: FORMAL SPECIALIST REFERRAL LETTERS
  // -------------------------------------------------------------
  const doctor_referrals: DoctorReferral[] = [
    {
      id: 'ref_001',
      referral_number: 'REF-2026-00104',
      patient_id: 'pat_008', // Carlos Alvarez
      referring_doctor_id: 'doc_003', // Dr. Bautista (General Medicine)
      receiving_specialty: 'Cardiology',
      receiving_doctor_name: 'Dr. Maria Lourdes Santos / Adult Cardiology',
      receiving_clinic_branch: 'MediQueue Main Flagship Center',
      priority: 'Routine',
      reason_for_referral: 'Evaluation of recurrent exertional chest tightness, borderline elevated resting BP (145/92 mmHg), and family history of premature coronary artery disease.',
      clinical_summary: '52-year-old male with 2-month history of retrosternal discomfort during brisk walking. Resting 12-lead ECG shows non-specific ST-T wave changes in inferior leads. Endorsed for comprehensive 2D-Echocardiogram with Doppler and Treadmill Exercise Stress Test.',
      relevant_vitals: 'BP: 145/92 mmHg • HR: 78 bpm • SpO2: 98% • BMI: 27.4 kg/m²',
      attached_medications: 'Amlodipine 5mg OD, Aspirin 80mg OD',
      attached_lab_results: 'Lipid Panel: Total Chol 238 mg/dL, LDL 154 mg/dL. Fasting Blood Glucose: 98 mg/dL.',
      status: 'pending',
      valid_until: '2026-10-10',
      created_at: '2026-09-09T15:20:00Z',
    },
    {
      id: 'ref_002',
      referral_number: 'REF-2026-00105',
      patient_id: 'pat_002', // Bea Gonzales
      referring_doctor_id: 'doc_001', // Dr. Santos (Internal Medicine)
      receiving_specialty: 'Pulmonology',
      receiving_doctor_name: 'Pulmonary Diagnostic Unit',
      receiving_clinic_branch: 'MediQueue BGC Health & Diagnostic Hub',
      priority: 'Urgent',
      reason_for_referral: 'Recurrent bronchospastic attacks unresponsive to short-acting beta-agonists. Requesting formal Spirometry with pre/post bronchodilator evaluation.',
      clinical_summary: '28-year-old female with persistent nocturnal cough and episodic expiratory wheezing over past 4 weeks despite oral corticosteroids and inhaled therapy. For specialist pulmonology management and allergy testing.',
      relevant_vitals: 'BP: 118/76 mmHg • HR: 86 bpm • SpO2: 96% on room air • RR: 20 cpm',
      attached_medications: 'Salbutamol + Ipratropium MDI 2 puffs TID, Montelukast 10mg tab OD',
      attached_lab_results: 'Chest X-ray: Hyperaerated lung fields, no consolidations or effusions.',
      status: 'accepted',
      valid_until: '2026-09-25',
      created_at: '2026-09-08T16:00:00Z',
    },
  ];

  return {
    users,
    specializations,
    doctors,
    patients,
    doctor_schedules,
    appointments,
    queue,
    consultations,
    audit_logs,
    clinic_settings,
    notifications,
    vital_signs,
    lab_orders,
    billing_invoices,
    doctor_work_statuses,
    triages,
    pharmacy_items,
    dispense_records,
    lab_results,
    sms_logs,
    telemed_sessions,
    clinic_branches,
    medical_certificates,
    doctor_referrals,
  };
}
